# Generated by Django 6.0 on 2025-12-23 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='記録日')),
                ('clock_in_time', models.TimeField(blank=True, null=True, verbose_name='出勤時刻')),
                ('clock_out_time', models.TimeField(blank=True, null=True, verbose_name='退勤時刻')),
                ('break_start_time', models.TimeField(blank=True, null=True, verbose_name='休憩開始時刻')),
                ('break_end_time', models.TimeField(blank=True, null=True, verbose_name='休憩終了時刻')),
                ('total_work_time', models.DurationField(blank=True, null=True, verbose_name='実働時間')),
                ('total_break_time', models.DurationField(blank=True, null=True, verbose_name='休憩時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '勤怠記録',
                'verbose_name_plural': '勤怠記録',
                'ordering': ['-date', 'user'],
                'indexes': [models.Index(fields=['user', 'date'], name='attendance__user_id_f0d554_idx'), models.Index(fields=['date'], name='attendance__date_337b1d_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
